### ISSUE TITLE
Calendar / clock widget / lock screen - eng

### ISSUE THREAD

**Issue by 77v77** [MASVA/MA-XML-10.0-CROATIAN#1]
Pozdrav ekipa, primjetio sam da su lock screen, kalendar i widget od sata/vremenske prognoze na engleskom jeziku. Može li se to riješiti? ps. MASVA pozdrav od kolege s Red-Gsm foruma (v7)!

Hi guys, I noticed that lock screen, calendar & clock/weather widget are on English language instead on Croatian. Can this be fixed? Thanks!

**Comment by MASVA** [comment]
daj screenshot da vidim i koji je ROM u pitanju

**Comment by 77v77** [comment]
![screenshot_2018-09-19-21-53-41-091_com miui home](https://user-images.githubusercontent.com/43421444/45777724-eb8e9700-bc56-11e8-9989-8863008bb65c.png)
![screenshot_2018-09-19-21-53-34-729_com android calendar](https://user-images.githubusercontent.com/43421444/45777729-f0ebe180-bc56-11e8-8c37-36c3caa00fe5.png)
![screenshot_2018-09-19-21-53-28-769_lockscreen](https://user-images.githubusercontent.com/43421444/45777734-f47f6880-bc56-11e8-9c19-2a9ad7f6bfdc.png)

**Comment by MASVA** [comment]
nema to veze s eu prijevodom ovdje, tu je sve u redu
to je global ROM kojeg radi lik na crowdinu, ne radim ja više, ali pogledam
lp

**Comment by 77v77** [comment]
Što se ROMa tiče, tablet sam uzeo preko AliExpressa i ima naziv "Global ROM". E sad tsblet mi je stigao danas pa se još učim gdje je i što je što. Ako se ne varam, ja zapravo imam fake-global rom pa je moguće da zato ne funkcionira prijevod kako bi trebao...
![img_20180919_215807](https://user-images.githubusercontent.com/43421444/45777995-a159e580-bc57-11e8-82df-243fe6bf0b07.jpg)

**Comment by 77v77** [comment]
> nema to veze s eu prijevodom ovdje, tu je sve u redu
> to je global ROM kojeg radi lik na crowdinu, ne radim ja više, ali pogledam
> lp

Probam skinuti ovaj EU ROM ako kažeš da tu sve šljaka. Hvala! Lp

**Comment by MASVA** [comment]
provjeri ako ti je bootloader otključan
ako je stavi twrp i pukni gore .eu ROM
ja bi....

sri, 19. ruj 2018. u 22:02 77v77 <notifications@github.com> napisao je:

**Comment by MASVA** [comment]
ako je BL otključan, flešaj TWRP , format data ( time brišeš sve na mobu i
eventualno ostatke tog fake ROM-a)
 restart u TWRP obavezno
kopiraj ROM putem računala i flash

sri, 19. ruj 2018. u 22:03 77v77 <notifications@github.com> napisao je:

**Comment by 77v77** [comment]
Otključan je BL. Thx na uputi, poigrat ću se s tim svakako, moram iskopati neke upute i malo se upoznati s procedurom. Inače, taj EU rom bi trebao biti stabilan i imati ok prijevod + Google Play?

**Comment by MASVA** [comment]
da, prijevod je ažuran, osobo ga radim svakodnevno + google aplikacije
vozim developer ROM i jako zadovoljan
stable izbjegavam, neka te naziv ne buni
ako zapneš što i kako, javi

sri, 19. ruj 2018. u 22:11 77v77 <notifications@github.com> napisao je:
