### ISSUE TITLE
Aplikacija "Kamera" - prijevod

### ISSUE THREAD

**Issue by 77v77** [MASVA/MA-XML-10.0-CROATIAN#2]
Pozdrav, u aplikaciji "Kamera" ne postoji prijevod za "tonove kože". Prilikom pritiska na ikonu zvjezdice na dnu ekrana stoji engleski naziv izbornika "Highlight skin tones".  Lp

Uređaj: Xiaomi Mi Pad 4
ROM: xiaomi.eu_multi_MIPAD4_8.9.20_v10-8.1

**Comment by MASVA** [comment]
radi se na tome
thx

**Comment by 77v77** [comment]
Hvala! ps. vrhunski je složen EU.ROM, drago mi je da sam poslušao tvoju preporuku
