### ISSUE TITLE
MIUI 10 8.9.20. [Mi Pad 4 Screen Mirroring prijevod]

### ISSUE THREAD

**Issue by 77v77** [MASVA/MA-XML-10.0-CROATIAN#3]
Bok! Screen Mirroring ilti "Bežićni zaslon" kako si ga preveo u postavkama uređaja nije do kraja preveden. Screenshot u privitku. Pozdrav! :)
![screenshot_2018-10-10-16-24-26-446_com android settings](https://user-images.githubusercontent.com/43421444/46743445-5d339100-cca9-11e8-8640-f2aaa5bedc3c.png)

**Comment by MASVA** [comment]
ispravljeno
drugi petak bude dostupno
