### ISSUE TITLE
Cleaning recent apps

### ISSUE THREAD

**Issue by fzunic7** [MASVA/MA-XML-10.0-CROATIAN#4]
On Pocophone F1 miui 10.1.0.3 stable when cleaning all recent apps it says ociscenjo instead of ocisceno

**Comment by MASVA** [comment]
Global ROM ili .EU?

**Comment by fzunic7** [comment]
Global

**Comment by MASVA** [comment]
Prijaviti treba na drugo mjesto kako rekoh zadnji puta, ne ovdje ali riješim
