### ISSUE TITLE
MIUI 10.3 (9.2.21 - weekly)

### ISSUE THREAD

**Issue by 77v77** [MASVA/MA-XML-10.0-CROATIAN#5]
Pozdrav MASVA! 

Na verziji v9.2.21 (za Mi Pad 4) problem s prijevodom postoji u:

**- Kalendar**
1) piše "_week_" i "_day_" umjesto "tjedan" i "dan" kao u prethodnoj verziji FW-a.
2) kada dodaješ događaj u kalendar, praktički cijeli izbornik nije preveden (_Show me as_, _Privacy_, _Add reminder_, _Repeat_, _Guests_)

**- Kalkulator**
1) kada uđeš u kalkulator, umjesto "kalkulator, konverter i zadužnica" piše "_Calculator_, _Converter_ i _Mortgage_"
2) pod izbornikom "_mortgage_ / zadužnica" pod "kamate" piše "_Enter interest rate_"

**Comment by MASVA** [comment]
Bok, EU ROM?
--
Sent from myMail for Android ponedjeljak, 25 veljače 2019, 11:04AM +01:00 from 77v77  notifications@github.com :

**Comment by 77v77** [comment]
EU ROM, točno

LINK: https://xiaomi.eu/community/threads/9-2-21.49315/

**Comment by MASVA** [comment]
Kod mene na mi8 je kalendar ok
Kalkulator pošteljam za drugi tjedan
--
Sent from myMail for Android ponedjeljak, 25 veljače 2019, 11:08AM +01:00 from 77v77  notifications@github.com :

**Comment by 77v77** [comment]
Na Mi Pad 4 nažalost ne dela kak spada... Ok hvala za ovo! :D
