### ISSUE TITLE
MIUI 10.4 (9.5.16 - weekly)

### ISSUE THREAD

**Issue by 77v77** [MASVA/MA-XML-10.0-CROATIAN#6]
Pozdrav MASVA, prijavljujem probleme koji su se pojavili na Mi Pad 4 nakon updatea na MIUI 10.4 - (9.5.16 weekly).

**1. Vrijeme**: aplikacija je izgubila prijevod vremenskih prilika (cloudy/thunderstorm/rainy/sunny i sl.)

![Screenshot_2019-05-19-12-59-45-258_com miui weather2](https://user-images.githubusercontent.com/43421444/57984857-3d92f100-7a60-11e9-8978-f88fd0a61b7e.png)

![Screenshot_2019-05-19-13-00-02-655_com miui weather2](https://user-images.githubusercontent.com/43421444/57984862-4257a500-7a60-11e9-8afb-b59cad21f25c.png)

**2. Prilikom izlaska iz igara** umjesto "Prekini ubrzavanje/Ubrzavanje uspješno" se pojavljuje "Stop boosting/Boosted successfully". Također, cijeli izbornik "Boost games" je na engleskom jeziku.

![Screenshot_2019-05-19-17-55-37-691_com gameloft android ANMP GloftA8HM](https://user-images.githubusercontent.com/43421444/57984882-674c1800-7a60-11e9-8eb3-fe93752a98aa.png)

![Screenshot_2019-05-19-17-55-44-626_com miui home](https://user-images.githubusercontent.com/43421444/57984883-6adf9f00-7a60-11e9-80d9-ae3ca3097302.png)

**3. Xioami.EU alati:** potrebno prevesti stavke sa slike (wallpaper carousel/Hardware test/"Alati %1$s"
![Screenshot_2019-05-19-13-01-55-444_pl zdunex25 xiaomieutools](https://user-images.githubusercontent.com/43421444/57984890-88ad0400-7a60-11e9-9081-dfefd50eb607.png)

**4.Isključivanje uređaja:** zbog dugačkog naziva _"Ponovno pokreni_ tekst se vidi na rubu zaslona:
![Screenshot_2019-05-19-13-02-33-852_com miui home](https://user-images.githubusercontent.com/43421444/57984915-b98d3900-7a60-11e9-89e0-16f53a6c44c6.png)

**Comment by MASVA** [comment]
moram provjeriti do je zapelo
možda nije dodan taj prijevod za ovotjedni eu ROM
za vrijeme, te stringove nisam uopće dirao a i kod mene je isto
za game booster, stringovi su prevedeni, provjerim zašto ih u mipad 4 nema, kod mene na mi8 sve prevedeno
Xiaomi.EU alati je apliakcija samo za mipad4 , moram je izvaditi iz ROM-a pa napraviti diff,
ako imaš ROOT, pošalji mi apk
4.Isključivanje uređaja: zbog dugačkog naziva "Ponovno pokreni tekst se vidi na rubu zaslona: a kaj da stavimo kraće, prijedlog?

**Comment by 77v77** [comment]
Ne znam što se dogodilo s Vremenskom prognozom, bilo je sve ok, a što se Game boostera tiče, on od starta nije preveden na Mi Pad 4, niti u jednom Weekly updateu nije bilo na HR. Btw. još jedna napomena: **Kalkulator** ima slovo "K" napisano veliko u sredini riječi -> _Mi Kal**K**ulator_ se zove aplikacija. 

Što se tiče prijevoda "Ponovno pokreni", možemo ga staviti kao _restart_. Kada dugo držiš tipku za isključivanje uređaja, pojavi se izbornik/tipka na kojem inicijalno piše "ponovno pokreni". Ako taj dio prebacimo u _restart_, smatram da nije toliki problem jer postoji još jedan dodatni korak koji slijedi kada pristisneš na tipku _restart_ koji te pita "Dodirni za ponovno pokretanje" čime je riječ 100% prevedena na hrvatski jezik. Čisto razmišljam naglas, time smo izbjegli problem sa dužinom, a opet imamo prijevod na sljedećem koraku. Pretražio sam cijeli net i nažalost nisam našao neki smisleni sinonim za sporni izraz :) 

![Screenshot_2019-05-19-20-36-31-844_com android vending](https://user-images.githubusercontent.com/43421444/57986489-e3048f80-7a75-11e9-9fca-3c29ed2b684f.png)

**Comment by 77v77** [comment]
Pozdrav, 9.5.23 i dalje nema prijevod Vremenske prognoze (i ostalog), planiraš li možda uskoro baciti update prijevoda? Thx

**Comment by MASVA** [comment]
vrijeme je riješeno, ostalo rješavam u hodu, lp
